"use client";

import { BriefcaseBusiness, ExternalLink, LoaderCircle, LogOut, Radar, Search, Settings2 } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";

type Job = { id: string; title: string; company: string; ats: string; location: string | null; remote: boolean | null; employmentType: string | null; department: string | null; postedAt: string | null; postedText: string | null; postedDaysAgo: number | null; url: string };
type Run = { id: string; generated_at: string; source_count: number; fetched_count: number; matched_count: number };

export function Dashboard() {
  const [session, setSession] = useState<Session | null>(null); const [run, setRun] = useState<Run | null>(null); const [jobsData, setJobsData] = useState<Job[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [isSignUp, setIsSignUp] = useState(false); const [authBusy, setAuthBusy] = useState(false);
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession)); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!session) return; setLoading(true); (async () => { const { data: latest, error: runError } = await supabase.from("role_radar_runs").select("*").order("generated_at", { ascending: false }).limit(1).maybeSingle(); if (runError) throw runError; if (!latest) return; const { data: rows, error: jobsError } = await supabase.from("role_radar_jobs").select("*").eq("last_seen_run_id", latest.id).order("posted_days_ago", { ascending: true }).order("title"); if (jobsError) throw jobsError; setRun(latest); setJobsData((rows ?? []).map((job) => ({ id: job.id, title: job.title, company: job.company, ats: job.ats, location: job.location, remote: job.remote, employmentType: job.employment_type, department: job.department, postedAt: job.posted_at, postedText: job.posted_text, postedDaysAgo: job.posted_days_ago, url: job.url }))); })().catch(() => setError("Your account is signed in, but it has not been granted Role Radar access yet.")).finally(() => setLoading(false)); }, [session]);
  const jobs = useMemo(() => { const needle = query.toLowerCase(); return !needle ? jobsData : jobsData.filter((job) => `${job.title} ${job.company} ${job.location} ${job.department}`.toLowerCase().includes(needle)); }, [jobsData, query]);
  async function authenticate(event: FormEvent) { event.preventDefault(); setAuthBusy(true); setError(""); const result = isSignUp ? await supabase.auth.signUp({ email, password, options: { emailRedirectTo: window.location.origin } }) : await supabase.auth.signInWithPassword({ email, password }); if (result.error) setError(result.error.message); else if (isSignUp) setError("Check your email to confirm your account, then sign in."); setAuthBusy(false); }
  if (!session) return <main className="auth-page"><div className="auth-card"><div className="brand auth-brand"><span className="brand-mark"><Radar size={20} /></span><span>Role Radar</span></div><p className="eyebrow">Private job intelligence</p><h1>{isSignUp ? "Create your account" : "Welcome back"}</h1><p>Sign in to view your private, Supabase-backed job pipeline.</p><form onSubmit={authenticate}><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></label><label>Password<input required type="password" minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={isSignUp ? "new-password" : "current-password"} /></label>{error && <p className="auth-error" role="alert">{error}</p>}<button disabled={authBusy}>{authBusy ? "Working…" : isSignUp ? "Create account" : "Sign in"}</button></form><button className="text-button" onClick={() => { setIsSignUp(!isSignUp); setError(""); }}>{isSignUp ? "Already have an account? Sign in" : "Need an account? Sign up"}</button></div></main>;
  return <main><header className="topbar"><div className="brand"><span className="brand-mark"><Radar size={20} /></span><span>Role Radar</span></div><div className="topbar-note"><span>{session.user.email}</span><button className="logout" onClick={() => supabase.auth.signOut()}><LogOut size={15} />Sign out</button></div></header><section className="hero"><div><p className="eyebrow">Your focused job pipeline</p><h1>See the roles worth<br />your attention.</h1><p className="hero-copy">Your local ATS-Scrapers job runs publish directly to Supabase. This dashboard always reads the latest matching roles.</p></div><div className="scan-status"><span className={run ? "status-dot" : "status-dot idle"} /><span>{run ? `Updated ${new Date(run.generated_at).toLocaleString()}` : "Awaiting first scan"}</span></div></section>{error && <p className="feedback error" role="alert">{error}</p>}<section className="stats" aria-label="Pipeline summary"><Metric label="Companies" value={run?.source_count ?? 0} /><Metric label="Relevant roles" value={run?.matched_count ?? 0} /><Metric label="Listings scanned" value={run?.fetched_count ?? 0} /></section><section className="workspace"><aside className="control-panel"><div className="panel-heading"><div><p className="eyebrow">Data source</p><h2>Supabase sync</h2></div><BriefcaseBusiness size={21} /></div><div className="local-note"><Settings2 size={17} /><p>Manage company links and filters locally, then run <code>generate_jobs.py</code> to publish a new scan.</p></div></aside><section className="results-panel"><div className="panel-heading results-heading"><div><p className="eyebrow">Matching positions</p><h2>Latest opportunities</h2></div><label className="search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search results" aria-label="Search results" /></label></div>{loading ? <div className="empty-state"><LoaderCircle className="spin" /><p>Loading current job data…</p></div> : jobs.length ? <div className="table-wrap"><table><thead><tr><th>Position</th><th>Company</th><th>Location</th><th>Created</th><th aria-label="Open job" /></tr></thead><tbody>{jobs.map((job) => <tr key={job.id}><td><a href={job.url} target="_blank" rel="noreferrer" className="job-title">{job.title}</a><span className="job-meta">{job.department || job.employmentType || job.ats}</span></td><td>{job.company}</td><td>{job.location || "—"}{job.remote && <span className="remote-tag">Remote</span>}</td><td><strong>{formatPosted(job)}</strong></td><td><a className="open-link" href={job.url} target="_blank" rel="noreferrer" aria-label={`Open ${job.title} at ${job.company}`}><ExternalLink size={17} /></a></td></tr>)}</tbody></table></div> : <div className="empty-state"><Radar size={31} /><h3>Your account has no visible scan yet</h3><p>Confirm your account has access, then publish a local scan.</p></div>}</section></section></main>;
}
function formatPosted(job: Job) { if (job.postedDaysAgo === 0) return "Today"; if (job.postedDaysAgo === 1) return "Yesterday"; if (job.postedDaysAgo !== null) return `${job.postedDaysAgo}d ago`; if (job.postedAt) return new Date(job.postedAt).toLocaleDateString(); return job.postedText || "Unknown"; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
